"""Ajout de la table paiement

Revision ID: 1a9f9f303340
Revises: 354c6730dd03
Create Date: 2025-06-25 02:12:53.981533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9f9f303340'
down_revision = '354c6730dd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apikey', sa.String(length=40), nullable=False),
    sa.Column('site_id', sa.String(length=8), nullable=False),
    sa.Column('transaction_id', sa.String(length=250), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('notify_url', sa.String(length=250), nullable=False),
    sa.Column('return_url', sa.String(length=100), nullable=False),
    sa.Column('channels', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('abonnement_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['abonnement_id'], ['abonnements.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paiements')
    # ### end Alembic commands ###
