"""Optimisation du modèle Scans

Revision ID: 354c6730dd03
Revises: aa0e4c942d74
Create Date: 2025-06-24 20:20:06.930617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354c6730dd03'
down_revision = 'aa0e4c942d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('device_identifier',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Format: brand:model:restaurant_id:YYYY-MM-DD',
               existing_nullable=False)
        batch_op.drop_index('idx_restaurant_device')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('idx_restaurant_device', ['restaurant_id', 'device_brand', 'device_model'], unique=False)
        batch_op.alter_column('device_identifier',
               existing_type=sa.VARCHAR(length=255),
               comment='Format: brand:model:restaurant_id:YYYY-MM-DD',
               existing_nullable=False)

    # ### end Alembic commands ###
