"""Ajout du champ updated_at adans la table paiement

Revision ID: 6366d9f22e87
Revises: d1126e6c1af1
Create Date: 2025-06-25 04:04:04.981388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6366d9f22e87'
down_revision = 'd1126e6c1af1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
