"""Ajout de la table scan avec de nouveau champs

Revision ID: 8a0ae2979a84
Revises: e3056c253253
Create Date: 2025-06-24 16:08:15.081179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0ae2979a84'
down_revision = 'e3056c253253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abonnements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_abonnement', sa.String(length=15), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('dateDebut', sa.DateTime(), nullable=False),
    sa.Column('dateFin', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=15), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_brand', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('device_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('os_family', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('os_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('browser_family', sa.String(length=50), nullable=True))
        batch_op.alter_column('restaurant_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.alter_column('restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('restaurant_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.drop_column('browser_family')
        batch_op.drop_column('os_version')
        batch_op.drop_column('os_family')
        batch_op.drop_column('device_model')
        batch_op.drop_column('device_brand')

    op.drop_table('abonnements')
    # ### end Alembic commands ###
