"""Optimisation du modèle Scans

Revision ID: aa0e4c942d74
Revises: 4b6f5f5dd379
Create Date: 2025-06-24 19:51:32.762576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa0e4c942d74'
down_revision = '4b6f5f5dd379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('device_brand', sa.String(length=100), nullable=False),
    sa.Column('device_model', sa.String(length=100), nullable=False),
    sa.Column('device_identifier', sa.String(length=255), nullable=False, comment='Format: brand:model:restaurant_id:YYYY-MM-DD'),
    sa.Column('os_family', sa.String(length=50), nullable=False),
    sa.Column('os_version', sa.String(length=50), nullable=False),
    sa.Column('browser_family', sa.String(length=50), nullable=False),
    sa.Column('browser_version', sa.String(length=50), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('number_scan_device', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_identifier'),
    sa.UniqueConstraint('device_identifier', name='unique_device_scan_per_day')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('idx_restaurant_device', ['restaurant_id', 'device_brand', 'device_model'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index('idx_restaurant_device')

    op.drop_table('scans')
    # ### end Alembic commands ###
