"""Ajout de la table paiement 2

Revision ID: d1126e6c1af1
Revises: 1a9f9f303340
Create Date: 2025-06-25 02:49:38.809864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1126e6c1af1'
down_revision = '1a9f9f303340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode_paiement', sa.String(length=50), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['transaction_id'])
        batch_op.drop_column('site_id')
        batch_op.drop_column('notify_url')
        batch_op.drop_column('return_url')
        batch_op.drop_column('apikey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paiements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apikey', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('return_url', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('notify_url', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('site_id', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('mode_paiement')

    # ### end Alembic commands ###
