"""Migration de la bd SGR

Revision ID: e3056c253253
Revises: 
Create Date: 2025-06-23 23:52:58.798583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3056c253253'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_entreprise', sa.String(length=120), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('adresse', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=10), nullable=False),
    sa.Column('qr_code_url', sa.String(length=255), nullable=False),
    sa.Column('qr_code_img', sa.String(length=120), nullable=False),
    sa.Column('hash_url', sa.String(length=128), nullable=False),
    sa.Column('logo', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('hash_url'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('abonnements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_abonnement', sa.String(length=15), nullable=False),
    sa.Column('montant', sa.Integer(), nullable=False),
    sa.Column('dateDebut', sa.DateTime(), nullable=False),
    sa.Column('dateFin', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=15), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=False),
    sa.Column('prix', sa.Integer(), nullable=False),
    sa.Column('date_jour', sa.DateTime(), nullable=False),
    sa.Column('statut', sa.String(length=15), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('categories_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plats')
    op.drop_table('scans')
    op.drop_table('categories')
    op.drop_table('abonnements')
    op.drop_table('users')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
